apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-kafka-egress
  namespace: compute     # đổi theo namespace bạn đang chạy Spark
spec:
  selector: all()          # áp dụng cho toàn bộ pod trong namespace
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 192.168.73.0/24   
        ports:
          - 9092              

    - action: Allow
      protocol: UDP
      destination:
        nets:
          - 192.168.73.0/24
        ports:
          - 9092              

    - action: Allow
