apiVersion: v1
kind: Service
metadata:
  name: spark-ui
  namespace: compute
spec:
  type: NodePort
  selector:
    spark-role: driver
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 30040
