apiVersion: v1
kind: Secret
metadata:
  name: openmetadata-authentication-secret
  namespace: openmetadata
type: Opaque
stringData:
  AUTHENTICATION_PUBLIC_KEYS: '["https://keycloak.datalabutehy.com/realms/data-team/protocol/openid-connect/certs"]'
  AUTHENTICATION_JWT_PRINCIPAL_CLAIMS: '["email","preferred_username","sub"]'
  AUTHENTICATION_PROVIDER: '"custom-oidc"'
  CUSTOM_OIDC_AUTHENTICATION_PROVIDER_NAME: '"Keycloak"'
  AUTHENTICATION_RESPONSE_TYPE: '"code"'
  AUTHENTICATION_AUTHORITY: '"https://keycloak.datalabutehy.com/realms/data-team"'
  AUTHENTICATION_CLIENT_ID: '"openmetadata"'
  AUTHENTICATION_CLIENT_TYPE: '"confidential"'
  AUTHENTICATION_CALLBACK_URL: '"https://openmetadata.datalabutehy.com/callback"'
  AUTHENTICATION_ENABLE_SELF_SIGNUP: "true"
  AUTHENTICATION_ENABLE_AUTO_REDIRECT: "false"
  FORCE_SECURE_SESSION_COOKIE: "true"
  OIDC_CLIENT_ID: '"openmetadata"'
  OIDC_TYPE: '"customOidc"'
  OIDC_CLIENT_SECRET: '"s3cXPbigflkwFSot9ckf4kBERTHwRWhn"'
  OIDC_SCOPE: '"openid email profile"'
  OIDC_DISCOVERY_URI: '"https://keycloak.datalabutehy.com/realms/data-team/.well-known/openid-configuration"'
  OIDC_USE_NONCE: "true"
  OIDC_PREFERRED_JWS: '"RS256"'
  OIDC_RESPONSE_TYPE: '"code"'
  OIDC_DISABLE_PKCE: "true"
  OIDC_CALLBACK: '"https://openmetadata.datalabutehy.com/callback"'
  OIDC_SERVER_URL: '"https://openmetadata.datalabutehy.com"'
  OIDC_CLIENT_AUTH_METHOD: '"client_secret_post"'
---
apiVersion: v1
kind: Secret
metadata:
  name: openmetadata-authorizer-secret
  namespace: openmetadata
type: Opaque
stringData:
  AUTHORIZER_CLASS_NAME: '"org.openmetadata.service.security.DefaultAuthorizer"'
  AUTHORIZER_REQUEST_FILTER: '"org.openmetadata.service.security.JwtFilter"'
  AUTHORIZER_PRINCIPAL_DOMAIN: '"open-metadata.org"'
  AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN: "false"
  AUTHORIZER_ENABLE_SECURE_SOCKET: "false"
  AUTHORIZER_ADMIN_PRINCIPALS: '["admin","damquangthinh"]'
  AUTHORIZER_ALLOWED_DOMAINS: "[]"
  AUTHORIZER_ALLOWED_REGISTRATION_DOMAIN: '["all"]'
  AUTHORIZER_USE_ROLES_FROM_PROVIDER: "false"
  AUTHORIZER_DEFAULT_OAUTH_ROLE: '"DataConsumer"'
