apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: storage
spec:
  ports:
  - name: cluster
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  type: ClusterIP