apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/minio-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/minio-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/minio-2