apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/postgres