apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: orchestration
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: "gVZQ9N5wl4X5FfldC7aum34yNGwdnWmX3Z_5D225m6w="
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres.metastore.svc.cluster.local:5432/airflow"
  AIRFLOW__WEBSERVER__SECRET_KEY: "0715061ba7d3424d9b70bbaf63ed6f80"
