apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: nlhtungg/mbs-poc-airflow:1.0.0
          command: ["airflow", "scheduler"]
          envFrom:
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          ports:
            - containerPort: 8793
          readinessProbe:
            exec:
              command: ["bash", "-c", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
            initialDelaySeconds: 15
            periodSeconds: 30
    volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc