apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: ghostwood/airflow-mbs-test:2.7.4
          command: ["airflow", "webserver"]
          envFrom:
            - secretRef:
                name: airflow-secrets
          env:
            - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
              value: "config.hostname_callable.get_hostname"
            - name: AIRFLOW_SCHEDULER_SERVICE_NAME
              value: "airflow-scheduler.airflow.svc.cluster.local"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
