apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  namespace: orchestration
spec:
  type: NodePort
  selector:
    app: airflow-scheduler
  ports:
    - port: 8793
      targetPort: 8793
      nodePort: 30082
