executor: CeleryExecutor

airflow:
  image:
    repository: apache/airflow
    tag: "2.10.5"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30081
        protocol: TCP
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin

config:
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG:
    value: "True"
  AIRFLOW__WEBSERVER__BASE_URL:
    value: "http://localhost:8080"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
    value: "postgresql+psycopg2://hive:hive@postgres.metastore.svc.cluster.local:5432/airflow"
  AIRFLOW__CELERY__RESULT_BACKEND:
    value: "db+postgresql://hive:hive@postgres.metastore.svc.cluster.local:5432/airflow"

redis:
  enabled: true
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 512Mi

dags:
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 2Gi

logs:
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 2Gi
