apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: orchestration
spec:
  selector:
    matchLabels: &id001
      app: airflow-web
      role: web
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: airflow-web
        image: apache/airflow:2.7.3-python3.11
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        ports:
        - containerPort: 8080
  replicas: 1
