apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: orchestration
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /mnt/data/airflow-dags  # Thư mục trên node thật
