executor: CeleryExecutor

airflow:
  image:
    repository: apache/airflow
    tag: "2.10.5"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30081
        protocol: TCP
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin

config:
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG:
    value: "True"
  AIRFLOW__WEBSERVER__BASE_URL:
    value: "http://localhost:8080"

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: hostpath
      size: 512Mi

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  primary:
    persistence:
      enabled: true
      storageClass: hostpath
      size: 1Gi

dags:
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 2Gi

logs:
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 2Gi
