apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
  namespace: orchestration
spec:
  type: NodePort
  selector:
    app: airflow-webserver
  ports:
    - name: web
      protocol: TCP
      port: 8080           # Port trong cluster
      targetPort: 8080     # Port container
      nodePort: 32001      # Port public trên node (bạn có thể đổi)
