apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: orchestration
spec:
  selector:
    matchLabels: &id001
      app: airflow-worker
      role: worker
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: airflow-worker
        image: apache/airflow:2.7.3-python3.11
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        command:
        - airflow
        - celery
        - worker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - worker
            topologyKey: kubernetes.io/hostname
  replicas: 2
