executor: CeleryExecutor

airflow:
  image:
    repository: apache/airflow
    tag: "2.10.5"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

webserver:
  service:
    type: NodePort
    ports:
      http:
        nodePort: 30081
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin

config:
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG:
    value: "True"
  AIRFLOW__WEBSERVER__BASE_URL:
    value: "http://localhost:8080"

redis:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

dags:
  persistence:
    enabled: true
    size: 2Gi

logs:
  persistence:
    enabled: true
    size: 2Gi
