apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/airflow/postgres

