apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: orchestration
spec:
  selector:
    matchLabels: &id001
      app: redis
      role: cache
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
  replicas: 1
