apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-redis
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/airflow/redis