apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-postgres
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/your-project/zones/your-zone/disks/airflow-postgres
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-logs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwx
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/your-project/zones/your-zone/disks/airflow-logs
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-dags
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwx
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/your-project/zones/your-zone/disks/airflow-dags
    fsType: ext4
