# PV cho Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-postgres
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/postgres

---
# PV cho Logs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-logs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/logs
---
# PV cho DAGs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-dags
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/dags
