apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-postgres
  namespace: orchestration
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: StorageClass
metadata:
  name: filestore-rwx
provisioner: filestore.csi.storage.gke.io
parameters:
  tier: standard
  network: default
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true