apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-postgres
  namespace: orchestration
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-shared
  namespace: orchestration
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: enterprise-multishare-rwx
  resources:
    requests:
      storage: 2Gi