# =============================
# Airflow on-prem deployment
# =============================

# Executor mode
executor: CeleryExecutor

# Airflow core configuration
airflow:
  image:
    repository: nlhtungg/mbs-poc-airflow
    tag: "1.0.0"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

# Webserver service (expose NodePort)
webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30081
        protocol: TCP
  defaultUser:
    enabled: true
    username: admin
    password: admin
    role: Admin

# Airflow configuration (minimal + readable)
config:
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG:
    value: "True"
  AIRFLOW__WEBSERVER__BASE_URL:
    value: "http://localhost:8080"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
    value: "postgresql+psycopg2://airflow:airflow@postgres.orchestration.svc.cluster.local:5432/airflow"

# =============================
# Redis configuration
# =============================
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: true
    storageClassName: hostpath
    size: 512Mi

# =============================
# PostgreSQL configuration
# =============================
postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  primary:
    persistence:
      enabled: true
      storageClassName: hostpath
      size: 1Gi

# =============================
# Airflow DAGS storage
# =============================
dags:
  persistence:
    enabled: true
    storageClassName: hostpath
    accessMode: ReadWriteOnce
    size: 1Gi

# =============================
# Airflow Logs storage
# =============================
logs:
  persistence:
    enabled: true
    storageClassName: hostpath
    accessMode: ReadWriteOnce
    size: 2Gi

# =============================
# Triggerer & Workers
# =============================
workers:
  replicas: 1
triggerer:
  replicas: 1
scheduler:
  replicas: 1
