ingress:
  enabled: false

executor: "KubernetesExecutor"

serviceAccount:
  create: true
  name: airflow-worker

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: airflow-postgresql.orchestration.svc.cluster.local
    port: 5432
    db: airflow

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
  primary:
    persistence:
      enabled: true
      existingClaim: pvc-airflow-postgres
      size: 8Gi

defaultAirflowRepository: ghostwood/airflow
defaultAirflowTag: "2.0.3"
airflowVersion: "2.11.0"

config:
  core:
    executor: KubernetesExecutor
    dags_are_paused_at_creation: "True"
    load_examples: "False"

  kubernetes:
    namespace: orchestration

  kubernetes_executor:
    namespace: orchestration
    deleteWorkerPods: "True"

  logging:
    remoteLogging: true
    remoteLogConnId: minio_conn
    remoteBaseLogFolder: s3a://airflow-logs
    encryptS3Logs: false

dags:
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    storageClassName: "filestore-rwx"
    size: 10Gi

logs:
  persistence:
    enabled: true
    existingClaim: ""

extraVolumes:
  - name: airflow-shared
    persistentVolumeClaim:
      claimName: ~

extraVolumeMounts:
  - name: airflow-shared
    mountPath: /opt/airflow/dags
    subPath: dags

  - name: airflow-shared
    mountPath: /opt/airflow/logs
    subPath: logs

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: "300m"
      memory: "1Gi"

worker:
  persistence:
    enabled: false

triggerer:
  enabled: true
  persistence:
    enabled: false

redis:
  enabled: false

createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false