ingress:
  enabled: false

executor: "KubernetesExecutor"

serviceAccount:
  create: true
  name: airflow-worker

cleanup:
  enabled: true

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: airflow-postgresql.orchestration.svc.cluster.local
    port: 5432
    db: airflow

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
  primary:
    persistence:
      enabled: true
      existingClaim: pvc-airflow-postgres
      size: 8Gi

defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.11.0"
defaultAirflowDigest: ~
airflowVersion: "2.11.0"

config:
  core:
    executor: KubernetesExecutor

  kubernetes:
    namespace: orchestration

  kubernetes_executor:
    namespace: orchestration
  logging:
    remoteLogging: true
    remoteLogConnId: minio_conn
    remoteBaseLogFolder: s3a://airflow-logs
    encryptS3Logs: false

dags:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-shared
    accessMode: ReadWriteMany
    size: 2Gi

logs:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-shared
    accessMode: ReadWriteMany   
    size: 2Gi

worker:
  persistence:
    enabled: false

triggerer:
  enabled: true

redis:
  enabled: true

createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false