ingress:
  enabled: false

executor: "KubernetesExecutor"

serviceAccount:
  create: false
  name: airflow-worker

cleanup:
  enabled: true

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: airflow-postgresql.orchestration.svc.cluster.local
    port: 5432
    db: airflow
    sslmode: disable

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres

defaultAirflowRepository: ghostwood/airflow
defaultAirflowTag: "2.0.3"
defaultAirflowDigest: ~
airflowVersion: "2.10.3"

config:
  core:
    executor: KubernetesExecutor

  kubernetes:
    namespace: orchestration
    service_account_name: airflow-worker
    delete_worker_pods: true

  kubernetes_executor:
    namespace: orchestration
    service_account_name: airflow-worker

  logging:
    remoteLogging: true
    remoteLogConnId: minio_conn
    remoteBaseLogFolder: s3a://airflow-logs

dags:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-shared
    accessMode: ReadWriteMany

logs:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-shared

worker:
  persistence:
    enabled: false

triggerer:
  enabled: true

redis:
  enabled: true

createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false