apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: storage
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 2
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
        envFrom:
          - secretRef:
              name: minio-oidc-config
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: MINIO_ACCESS_KEY
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: MINIO_SECRET_KEY
        - name: MINIO_SERVER_URL
          value: "http://minio-svc-private.storage.svc.cluster.local:9000"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://minio-svc-private.storage.svc.cluster.local:9000"
        - name: MINIO_DOMAIN
          value: "minio.datalabutehy.com"
        args:
        - server
        - http://minio-0.minio.storage.svc.cluster.local/data
        - http://minio-1.minio.storage.svc.cluster.local/data
        - --console-address
        - :9001
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 20Gi
