apiVersion: v1
kind: Secret
metadata:
  name: keycloak-minio-setup
  namespace: storage
type: Opaque
stringData:
  KEYCLOAK_URL: "https://keycloak.datalabutehy.com"
  KEYCLOAK_ADMIN_REALM: "master"
  KEYCLOAK_ADMIN_USER: "temp-admin"
  KEYCLOAK_ADMIN_PASSWORD: "ddddf6aac8c14a6fbc011b1a74482b1a"
  KEYCLOAK_TARGET_REALM: "data-team"
  MINIO_CLIENT_ID: "minio"
  MINIO_PUBLIC_URL: "https://minio.datalabutehy.com"
