apiVersion: v1
kind: Service
metadata:
  name: hive-server
  namespace: metastore
spec:
  type: NodePort
  selector:
    app: hive-server
    role: hive-server
  ports:
  - port: 10000
    targetPort: 10000
    nodePort: 31000
    name: jdbc
