apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: metastore
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 31003
  selector:
    app: postgres
