apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: metastore
spec:
  type: NodePort
  selector:
    app: postgres
    role: db
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 5432
    name: p1
