apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: metastore
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/postgres  # Thư mục trên node thật
