# =========================
# PostgreSQL for demo/source database
# =========================
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: streaming
  labels:
    app: postgresdb
spec:
  selector:
    app: postgresdb
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-streaming-pvc
  namespace: streaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: streaming
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:15
          imagePullPolicy: IfNotPresent
          args:
            - postgres
            - -c
            - wal_level=logical
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "demo"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-streaming-pvc
