apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: starrocks
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 9030
    targetPort: 9030
  - name: web
    port: 8030
    targetPort: 8030
  - name: editlog
    port: 9010
    targetPort: 9010
  selector:
    app: fe
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
  namespace: starrocks
spec:
  type: ClusterIP
  ports:
  - name: heartbeat
    port: 9050
    targetPort: 9050
  - name: brpc
    port: 9060
    targetPort: 9060
  selector:
    app: be
---
apiVersion: v1
kind: Service
metadata:
  name: fe-lb
  namespace: starrocks
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 9030
    nodePort: 30030
  - name: web
    port: 8030
    nodePort: 30080
  selector:
    app: fe
