apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-operator-scratch
  namespace: starrocks
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: { requests: { storage: 400Mi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-initpwd-scratch
  namespace: starrocks
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: { requests: { storage: 400Mi } }