# PV cho Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-starrocks-fe-logs-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/starrocks/logs-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-starrocks-fe-logs-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/starrocks/logs-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-starrocks-fe-meta-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/starrocks/meta-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-starrocks-fe-meta-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/starrocks/meta-1