starrocks:
    initPassword:
        enabled: true
        # kubectl create secret generic starrocks-root-pass --from-literal=password='g()()dpa$$word'
        passwordSecret: starrocks-root-pass

    starrocksFESpec:
        replicas: 1
        service:
            type: LoadBalancer
        resources:
            requests:
                cpu: 0.5
                memory: 512Mi
        storageSpec:
            name: fe
            storageClassName: standard-rwo
            storageSize: 2Gi
            logStorageClassName: standard-rwo
            logStorageSize: 1Gi

    starrocksBeSpec:
        replicas: 1
        resources:
            requests:
                cpu: 1
                memory: 2Gi
            limits:
                cpu: 1
                memory: 2Gi
        storageSpec:
            name: be
            storageClassName: standard-rwo
            storageSize: 30Gi
            logStorageClassName: standard-rwo
            logStorageSize: 4Gi

    starrocksFeProxySpec:
        enabled: true
        service:
            type: LoadBalancer