starrocks:
    initPassword:
        enabled: true
        # kubectl create secret generic starrocks-root-pass --from-literal=password='g()()dpa$$word'
        passwordSecret: starrocks-root-pass

    starrocksFESpec:
        replicas: 2
        service:
            type: LoadBalancer
        resources:
            requests:
                cpu: 2
                memory: 2Gi
        storageSpec:
            name: fe
            storageSize: 2Gi
            logStorageSize: 2Gi

    starrocksBeSpec:
        replicas: 2
        resources:
            requests:
                cpu: 8
                memory: 16Gi
            limits:
                cpu: 8
                memory: 16Gi
        storageSpec:
            name: be
            storageSize: 30Gi
            logStorageSize: 4Gi

    starrocksFeProxySpec:
        enabled: true
        service:
            type: LoadBalancer