apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: orchestration
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow-postgresql.orchestration.svc.cluster.local:5432/airflow
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__CORE__HOSTNAME_CALLABLE: config.hostname_callable.get_hostname
  AIRFLOW_SCHEDULER_SERVICE_NAME: airflow-scheduler.orchestration.svc.cluster.local