apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-site
  namespace: metastore
  labels:
    app: hive
data:
  hive-site.xml: |-
    <configuration>
    	<!-- Kết nối Metastore -->
    	<property>
    		<name>javax.jdo.option.ConnectionURL</name>
    		<value>jdbc:postgresql://postgres.metastore.svc.cluster.local:5432/metastore</value>
    	</property>
    	<property>
    		<name>javax.jdo.option.ConnectionDriverName</name>
    		<value>org.postgresql.Driver</value>
    	</property>
    	<property>
    		<name>javax.jdo.option.ConnectionUserName</name>
    		<value>hive</value>
    	</property>
    	<property>
    		<name>javax.jdo.option.ConnectionPassword</name>
    		<value>hive</value>
    	</property>
    	<property>
    		<name>fs.s3a.access.key</name>
    		<value>minioadmin</value>
    	</property>
    	<property>
    		<name>fs.s3a.secret.key</name>
    		<value>minio@demo!</value>
    	</property>
    	<property>
    		<name>fs.s3a.endpoint</name>
    		<value>http://minio-0.storage.svc.cluster.local:9000</value>
    	</property>
    	<property>
    		<name>fs.s3a.path.style.access</name>
    		<value>true</value>
    	</property>
    	<property>
    		<name>fs.s3a.impl</name>
    		<value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    	</property>
    	<property>
    		<name>hive.metastore.db.type</name>
    		<value>postgres</value>
    		<description>Metastore DB type: derby, mysql, postgres, oracle, mssql</description>
    	</property>
    	<property>
    		<name>hive.metastore.warehouse.dir</name>
    		<value>s3a://warehouse/</value>
    	</property>
    </configuration>