apiVersion: v1
kind: Service
metadata:
  name: postgres-metastore
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-metastore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-metastore-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-metastore
  template:
    metadata:
      labels:
        app: postgres-metastore
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: "hive"
            - name: POSTGRES_PASSWORD
              value: "hive"
            - name: POSTGRES_DB
              value: "metastore"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pg-metastore-pvc
