apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-site
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgres-metastore:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hive</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>true</value>
      </property>
    </configuration>
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  ports:
    - port: 9083
      targetPort: 9083
  selector:
    app: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: fetch-jars
          image: curlimages/curl:8.10.1
          command: ["/bin/sh","-c"]
          args:
            - >
              set -e;
              mkdir -p /opt/hive/lib;
              curl -L -o /opt/hive/lib/postgresql-42.6.2.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.2/postgresql-42.6.2.jar;
              curl -L -o /opt/hive/lib/hadoop-aws-3.3.4.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar;
              curl -L -o /opt/hive/lib/aws-java-sdk-bundle-1.12.367.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar;
          volumeMounts:
            - name: hive-lib
              mountPath: /opt/hive/lib
      containers:
        - name: metastore
          image: apache/hive:4.0.0
          env:
            - name: SERVICE_NAME
              value: "metastore"
            - name: HIVE_METASTORE_DB_TYPE
              value: "postgres"
            - name: HIVE_METASTORE_USER
              value: "hive"
            - name: HIVE_METASTORE_PASSWORD
              value: "hive"
            - name: HIVE_METASTORE_DB_HOST
              value: "postgres-metastore"
            - name: HIVE_METASTORE_DB_NAME
              value: "metastore"
            - name: DB_DRIVER
              value: "postgres"
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-conf
              mountPath: /opt/hive/conf
            - name: hive-lib
              mountPath: /opt/hive/lib
      volumes:
        - name: hive-conf
          configMap:
            name: hive-site
        - name: hive-lib
          emptyDir: {}
