apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      initContainers:
        - name: fetch-spark-jars
          image: curlimages/curl:8.10.1
          command: ["/bin/sh","-c"]
          args:
            - >
              set -e;
              mkdir -p /opt/spark/jars;
              curl -L -o /opt/spark/jars/hadoop-aws-3.3.4.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar;
              curl -L -o /opt/spark/jars/aws-java-sdk-bundle-1.12.367.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar;
              curl -L -o /opt/spark/jars/delta-spark_2.12-3.2.0.jar https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar;
              curl -L -o /opt/spark/jars/delta-storage-3.2.0.jar https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar;
          volumeMounts:
            - name: spark-jars
              mountPath: /opt/spark/jars
      containers:
        - name: worker
          image: spark:3.5.6-scala2.12-java11-python3-r-ubuntu
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER
              value: "spark://spark-master:7077"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spark-jars
              mountPath: /opt/spark/jars
            - name: hive-site
              mountPath: /opt/spark/conf/hive-site.xml
              subPath: hive-site.xml
      volumes:
        - name: spark-jars
          emptyDir: {}
        - name: hive-site
          configMap:
            name: hive-site
