apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hive:hive@postgres-metastore:5432/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://hive:hive@postgres-metastore:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: 31E1-24OEkjXpTnzoypiTODWKtA3GUlRuqZjnkc9e20=
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
