apiVersion: v1
kind: Namespace
metadata:
  name: metastore

---
apiVersion: v1
kind: Namespace
metadata:
  name: query

---
apiVersion: v1
kind: Namespace
metadata:
  name: compute

---
apiVersion: v1
kind: Namespace
metadata:
  name: orchestration

---
apiVersion: v1
kind: Namespace
metadata:
  name: storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: cdc

---
apiVersion: v1
kind: Namespace
metadata:
  name: warehouse

---
apiVersion: v1
kind: Namespace
metadata:
  name: streaming

---
apiVersion: v1
kind: Namespace
metadata:
  name: volume-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: deployer

---
apiVersion: v1
kind: Namespace
metadata:
  name: metadata

---
apiVersion: v1
kind: Namespace
metadata:
  name: cache

--- 
apiVersion: v1 
kind: Namespace
metadata:
  name: keycloak