apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres-nodeport
  namespace: orchestration
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/name: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP