apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker-access-spark
  namespace: compute
subjects:
  - kind: ServiceAccount
    name: airflow-worker          
    namespace: orchestration      
roleRef:
  kind: Role
  name: spark-role               
  apiGroup: rbac.authorization.k8s.io
