ingress:
  web:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: airflow.k8s.tailnet
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    tls:
      enabled: false

executor: "KubernetesExecutor"

serviceAccount:
  create: true
  name: airflow-worker

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: airflow-postgresql.orchestration.svc.cluster.local
    port: 5432
    db: airflow

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
  primary:
    persistence:
      enabled: true
      existingClaim: pvc-airflow-postgres
      size: 8Gi

defaultAirflowRepository: linhdv2312/airflow
defaultAirflowTag: "2.10.3"
airflowVersion: "2.10.3"

config:
  core:
    executor: KubernetesExecutor
    dags_are_paused_at_creation: "True"
    load_examples: "False"

  webserver:
    base_url: "http://airflow.k8s.tailnet:30296"
    enable_proxy_fix: "True"

  kubernetes:
    namespace: orchestration

  kubernetes_executor:
    namespace: orchestration
    deleteWorkerPods: "True"

  logging:
    remoteLogging: false

dags:
  persistence:
    enabled: true
    storageClassName: longhorn
    accessMode: ReadWriteMany
    size: 10Gi

  gitSync:
    enabled: true
    repo: "https://github.com/ghostWood1071/native-data-platform.git"
    branch: "master"
    rev: HEAD
    subPath: "orchestration/dags"
    period: 30s

logs:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: datalab

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: "300m"
      memory: "1Gi"

worker:
  persistence:
    enabled: false

triggerer:
  enabled: true
  persistence:
    enabled: false

redis:
  enabled: false

createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false