airflowVersion: 2.10.3
config:
  core:
    dags_are_paused_at_creation: "True"
    executor: KubernetesExecutor
    load_examples: "False"
  kubernetes:
    namespace: orchestration
  kubernetes_executor:
    deleteWorkerPods: "True"
    namespace: orchestration
  logging:
    remoteLogging: false
  webserver:
    base_url: http://airflow.k8s.tailnet:30296
    enable_proxy_fix: "True"
createUserJob:
  useHelmHooks: false
dags:
  gitSync:
    branch: master
    enabled: true
    period: 30s
    repo: https://github.com/ghostWood1071/native-data-platform.git
    rev: HEAD
    subPath: orchestration/dags
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    size: 10Gi
    storageClassName: longhorn
data:
  metadataConnection:
    db: airflow
    host: airflow-postgresql.orchestration.svc.cluster.local
    pass: postgres
    port: 5432
    protocol: postgresql
    user: postgres
defaultAirflowRepository: linhdv2312/airflow
defaultAirflowTag: 2.10.3
executor: KubernetesExecutor
images:
  airflow:
    pullPolicy: Always
ingress:
  web:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    enabled: true
    hosts:
    - name: airflow.k8s.tailnet
    ingressClassName: nginx
    path: /
    pathType: Prefix
    tls:
      enabled: false
logs:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
migrateDatabaseJob:
  useHelmHooks: false
postgresql:
  auth:
    password: postgres
    username: postgres
  enabled: true
  primary:
    persistence:
      enabled: true
      existingClaim: pvc-airflow-postgres
      size: 8Gi
redis:
  enabled: false
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
serviceAccount:
  create: true
  name: airflow-worker
triggerer:
  enabled: true
  persistence:
    enabled: false
webserver:
  defaultUser:
    enabled: true
    password: datalab
    username: admin
worker:
  persistence:
    enabled: false
